name: "Carnap Deploy"
description: "Deploys Carnap assignments automatically"
author: "Carnap Authors"
inputs:
  apiKey:
    required: true
    description: >-
      API key to use to authenticate to Carnap. Do not put the API key in
      your workflow file.


      You should set this to something like `$ {{ secrets.CARNAP_API_KEY }}`,
      without the space after the dollar sign.

  defaultVisibility:
    required: false
    default: Private
    description: >-
      Visibility setting for newly created files. Can be Public,
      InstructorsOnly, LinkOnly or Private.


      The permissions on existing files will not be changed.

  includeFiles:
    required: false
    default: '["*.md"]'
    description: >-
      Files that will be uploaded to Carnap. This is in the form of a JSON
      list inside a string, containing Unix-style globs matching file names
      to upload. These are evaluated relative to the root folder of the project
      without recursing into subdirectories.


      The default is to take every .md file in the root directory of the project.

  instanceUrl:
    required: false
    default: "https://carnap.io"
    description: "URL of the Carnap instance to deploy to"

runs:
  using: "node12"
  main: "dist/index.js"
