name: "Carnap Deploy"
description: "Deploys Carnap assignments automatically"
author: "Carnap Authors"
inputs:
  apiKey:
    required: true
    description: >-
      API key to use to authenticate to Carnap. Defaults to the GitHub secret
      CARNAP_API_KEY. Do not put the API key in your workflow file.

  defaultVisibility:
    required: false
    description: >-
      Visibility setting for newly created files. Can be Public,
      InstructorsOnly, LinkOnly or Private.


      The permissions on existing files will not be changed.
    default: Private

  includeFiles:
    required: false
    description: >-
      Files that will be uploaded to Carnap. This is in the form of a JSON
      list inside a string, containing Unix-style globs matching file names
      to upload. These are evaluated relative to the root folder of the project
      without recursing into subdirectories.


      The default is to take every .md file in the root directory of the project.
    default: '["*.md"]'

  instanceUrl:
    required: false
    description: "URL of the Carnap instance to deploy to"
    default: "https://carnap.io"

runs:
  using: "node12"
  main: "dist/index.js"
