name: 'Release changes on main to releases/v1 if they are ok'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run test
      - run: |
          npm run lint
      - run: |
          npm run build
      - run: |
          npm run package
      - run: |
          git add dist
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m 'build output'
          git push "$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" -f origin releases/v1
